#!/bin/bash

set -e

if [ "$VIRTUAL_ENV" != "" ]; then
  echo "You are in a virtual env.  exit with 'deactivate' before running this script"
  exit 1
fi
PVER=${1:-python3.8}

cd $(dirname $0)

mkdir -p app-data-$PVER
rm -rf pytest-$PVER
#python3.6 -m venv NAME
sudo apt install -y python3.8 python3-pip python3.8-dev

$PVER -m pip install virtualenv==20.14.1
$PVER -m virtualenv --no-pip --no-setuptools --app-data ./app-data-$PVER pytest-$PVER
sudo apt install -y libssh2-1-dev sshpass libbz2-dev liblzma-dev intltool libxml2-utils libglib2.0-dev-bin libpq-dev libgirepository1.0-dev postgresql-common cmake make libgtk-3-dev libssl-dev

source pytest-$PVER/bin/activate
curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py "pip==21.0" "setuptools==41.0.1" "wheel==0.37.1"
rm get-pip.py
pip config set global.disable-pip-version-check true

#get version of ssh2-python with find_eol
if [ ! -d ssh2-python ]; then
  git clone https://github.com/kurt-cb/ssh2-python.git
  cd ssh2-python
  git checkout -t origin/kurtgo-cb/newlibssh
  #git checkout 0.26.0
  cd ..
fi
#pip install ssh2-python==0.26.0

# install meld
if [ ! -d meld ]; then
  git clone https://gitlab.gnome.org/GNOME/meld.git
  cd meld
  git checkout meld-3-20
  cd ..
fi
# ln -s $(pwd)/meld/bin/meld pytest-$PVER/bin/meld
pip install pycairo PyGObject
pip install ./meld


export PYTHONIOENCODING=utf8
#pip install wheel
pip install pylibjpeg-libjpeg
pip install gitpython tblib requests inquirer pytest redexpect pyyaml parallel-ssh
pip install ./ssh2-python
pip install setuptools_rust rust tk
pip install -e src/rohan.meter.pkg
pip install --extra-index-url=http://kaizenbot-azure.rohan.com:18080 --trusted-host=kaizenbot-azure.rohan.com KaizenBot-Gen5RivaLibrary==1.4.6
pip install --extra-index-url=http://kaizenbot-azure.rohan.com:18080 --trusted-host=kaizenbot-azure.rohan.com KaizenBot-AppServLibrary==1.3.1
# work around wxPython not building with setuptools 50+
pip install pytest-html
pip install pytest-azurepipelines
pip install robotframework-ride

echo build VENV successful
echo
echo To activate:
echo source pytest-$PVER/bin/activate

